//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebInventoryEntities : DbContext
    {
        public WebInventoryEntities()
            : base("name=WebInventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<categoriesmaster> categoriesmaster { get; set; }
        public DbSet<city> city { get; set; }
        public DbSet<Country> Country { get; set; }
        public DbSet<customermaster> customermaster { get; set; }
        public DbSet<gstcat> gstcat { get; set; }
        public DbSet<productmaster> productmaster { get; set; }
        public DbSet<State> State { get; set; }
        public DbSet<suppliermaster> suppliermaster { get; set; }
        public DbSet<taxesmaster> taxesmaster { get; set; }
        public DbSet<uommaster> uommaster { get; set; }
    }
}
