//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class productmaster
    {
        public int ProductId { get; set; }
        public string ProductTaxable { get; set; }
        public string ProductType { get; set; }
        public string ProductName { get; set; }
        public string UnitoMesure { get; set; }
        public string AlternameUom { get; set; }
        public string TaxType { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Discount { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public string Description { get; set; }
        public string Hscno { get; set; }
    }
}
