//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class suppliermaster
    {
        public int SuppId { get; set; }
        public string CompanyName { get; set; }
        public string PhoneNo { get; set; }
        public string EmailId { get; set; }
        public string GSTIN { get; set; }
        public string PAN { get; set; }
        public string VAT { get; set; }
        public string SupCode { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
    }
}
