//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxesmaster
    {
        public int TaxMasterId { get; set; }
        public string TaxName { get; set; }
        public string TaxPercentage { get; set; }
        public string TaxType { get; set; }
        public string TaxStatus { get; set; }
        public string TaxRoundingMethod { get; set; }
        public string TaxGroups { get; set; }
        public string TaxSubGroups { get; set; }
    }
}
