//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class uommaster
    {
        public int uomId { get; set; }
        public string symbol { get; set; }
        public string formalName { get; set; }
        public Nullable<int> numberofdecimalPlaces { get; set; }
    }
}
